### ISSUE TITLE
PaureProject.get_files() not implemented

### ISSUE THREAD

**Issue by sakalosj** [packit-service/ogr#377] opened 2020-04-14 07:44 UTC
PaureProject.get_files() not implemented. Maybe not possible because pagure api doesnt provide any possiblity to get repository content.

**Comment by lbarcziova** [comment] 2020-04-14 08:19
This is duplicate of #310

**Comment by lachmanfrantisek** [comment] 2020-04-14 09:13
@lbarcziova thanks

**Closed** 2020-04-14 09:13 UTC
Labels: Pagure, duplicate, feature, needs-design
